### ISSUE TITLE
[Saulo] Super Aéreo travando no ar

### ISSUE THREAD

**Issue by nuzrub** [trajes-fatais/public_bugtracker#2]
**Descrição do Bug**
Bug reportado pelo "OutroEdu". Ao final do Super Aéreo do Saulo, ele trava no ar.

**Como Reproduzir**
https://discordapp.com/channels/786056516263608370/786056516758274050/787131547635286047
https://cdn.discordapp.com/attachments/786056516758274050/787131546079330304/Saulo_Bug.mp4

**Comment by andreonanim** [comment]
Resolvido.
