### ISSUE TITLE
[Sarah] Soco no chão da Sarah

### ISSUE THREAD

**Issue by BadBin** [trajes-fatais/public_bugtracker#4]
**Descrição do Bug**
O soco no chão (no qual deveria aparecer a mão em outro lugar mais a frente pra agarrar) não aparece nada. Em seguida, qualquer versão desse golpe não funciona mais.
Em algum momento o golpe voltou a funcionar, mas não sei o motivo.

**Como Reproduzir**
Basta correr e imediatamente fazer o referido golpe (a versão pra trás, que o mão alcança uma área mais curta).

**Comment by andreonanim** [comment]
Isso na verdade é o fallback do jogo... Precisamos melhorar isso enquanto notificação

**Comment by nuzrub** [comment]
Elaborando um pouco mais, quando não há gana suficiente para executar ataques alfa / beta, ocorrem ataques "fallback". 
Estes fallbacks são versões "falhas" dos ataques, que servem como indicador que não há recursos o suficiente no momento para executar a ação.
