### ISSUE TITLE
[Renato] [Sarah] Jogo congela quando partida encerra por tempo esgotado

### ISSUE THREAD

**Issue by mbc07** [trajes-fatais/public_bugtracker#5]
**Descrição do Bug**
Quando uma partida entre Renato e Sarah acaba devido ao tempo do round ter esgotado, o jogo congela.

**Como Reproduzir**
No modo Versus IA, selecione Renato como P1 e Sarah como P2, em seguida jogue a partida de maneira que ela termine por tempo esgotado. O jogo mostrará a mensagem "Tempo Esgotado" e reproduzirá a animação de vitória/derrota de cada personagem, mas em seguida irá congelar ao invés de prosseguir para a tela de resultados. 

A música de fundo e as animações das barras de vida/super continuarão normalmente, ainda é possível pausar/despausar o jogo pressionando a barra de espaços e até mesmo mudar a IA com as teclas PgUp/PgDown, no entanto o jogo não prosseguirá para a tela de resultados, sendo necessário sair com Alt+F4.

**Comment by nuzrub** [comment]
@mbc07 nesses casos que o jogo trava, se você estiver no modo desenvolvedor, pode apertar Shift+R para dar reload na cena. Dai a partida reseta e você não precisa fechar-abrir o jogo.

**Comment by nuzrub** [comment]
Consegui reproduzir aqui, mas o problema aparenta ser com o Renato apenas. Se jogar Sarah vs Lucy, por exemplo, a partida encerra sem problemas, mas Renato + Lucy não.

**Comment by andreonanim** [comment]
Resolvido

**Comment by andreonanim** [comment]
Esse problema já foi resolvido. É apenas um loop no arquivo do Renato.
