### ISSUE TITLE
tela de vitória travada

### ISSUE THREAD

**Issue by LinkFalcon** [trajes-fatais/public_bugtracker#6]
**Descrição do Bug**
quando o Cristiano esta no modo gana e ganha de sua versão B-side com um especial a tela fica travada na imagem de vitória, e o controle não funciona, não é possível fazer nada.

**Comment by andreonanim** [comment]
Não consegui reproduzir. Você conseguiu reproduzir ?

**Comment by mbc07** [comment]
Estava pra reportar um problema que acho que está relacionado:

* Selecione o modo Versus IA;
* O jogo prosseguirá para a tela de seleção de personagens (jogador 1 pode selecionar ambos os personagens);
* Luta começa, após a luta o jogo prossegue para a tela de vitória (jogador 1 pode navegar pelas opções, independente de qual personagem tenha vencido); 
* Ao escolher "Revanche", a partida reinicia com os mesmos personagens;
* Após a segunda luta, será mostrado a tela de vitória novamente, mas dessa vez somente o jogador 2 conseguirá navegar pelas opções (independente de qual personagem tenha vencido).

**Comment by nuzrub** [comment]
@mbc07 esse problema já parece ser mais de UI que de personagens. Poderia criar uma issue separada para ele?

**Comment by nuzrub** [comment]
@andreonanim também não consegui reproduzir pelo jogo, mas vou conferir pelas animações de vitória/derrota deles se tem algum loop errado
