### ISSUE TITLE
Menu durante uma luta está hipersensivel

### ISSUE THREAD

**Issue by JetKinen** [trajes-fatais/public_bugtracker#8]
**Descrição do Bug**
Jogando um 1v1 contra uma IA(Renato [eu] vs Lucy) em algum momento eu abri o menu shift para poder muda de personagem e o jogo aumenta a sensibilidade do WASD na tela em muito. assim um apertar anda tipo 7 vezes numa direção em um milisegundo. Quando eu vou pro menu de "deseja sair ou não" o jogo teve um crash e não conseguiu responder e travou de vez

**Como Reproduzir**
Consegui reproduzir. Eu acredito que tenha a ver com abrir o menu do jogo enquanto Lucy faz um dos supers dela.
Aqui segue um webm. O  webm tem um bitrate/FPS ruin pois eu acidentalmente gravei um gif ao inves de um mp4 o que comeu o FPS do jogo na gravação, mas a velocidade do menu no final tava muito mais rapida que o GIF mostra. Eventualmente quando o jogo vai para o "deseja sair da partida" o movimento tava tão rapido que o gif não ta conseguindo mostrar. Nesse momento eu apertei A pra testar velocidade e o jogo foi sozinho para a tela de seleção de personagem.

**Comment by JetKinen** [comment]
https://webmshare.com/play/DBgGz

Segue aqui o webm.

**Comment by nuzrub** [comment]
Esse é um bug conhecido :x 
Essa UI de pause da partida é uma bem provisória que foi feita lá no começo do projeto e está na fila pra ser trocada por uma UI nova, na mesma linha da tela de menu/seleção. Por ora, o plano é substituir essa tela mesmo.
Na nossa experiência e baseado em relatos passados, isso é um bug raro, ele acontece só raramente. Acontece o mesmo ai ou é sempre?
